name: Keep App Alive

# 设置定时任务：每天 UTC 时间 00:00 运行一次 (北京时间早上8点)
# 你也可以改为 '0 */12 * * *' 代表每12小时运行一次
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: # 允许你手动点击按钮运行测试

jobs:
  ping_app:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Ping Streamlit App
        run: |
          # 将下面的链接换成你的 App 地址
          curl -I https://ipn-hemorrhage-risk.streamlit.app/
